apiVersion: v1
kind: Service
metadata:
  name: cloud-db
  labels:
    app: cloud.greyscale.pe.kr
    tier: db
    version: "20180609"
spec:
  ports:
    - port: 5432
      name: postgresql
  selector:
    app: cloud.greyscale.pe.kr
    tier: db
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-postgresql
  labels:
    app: cloud.greyscale.pe.kr
    tier: db
    version: "20180609"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud.greyscale.pe.kr
        tier: db
        version: "20180609"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: postgres:alpine
          name: postgresql
          env:
          - name: POSTGRES_USER
            value: nextcloud
          - name: POSTGRES_DB
            value: nextcloud
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloud-db-pass
                key: password
          ports:
          - containerPort: 5432
            name: postgresql
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/postgresql" 
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-cache-db
  labels:
    app: cloud.greyscale.pe.kr
    tier: cache-db
    version: "20180609"
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: cloud.greyscale.pe.kr
    tier: cache-db
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-redis
  labels:
    app: cloud.greyscale.pe.kr
    tier: cache-db
    version: "20180609"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud.greyscale.pe.kr
        tier: cache-db
        version: "20180609"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: redis:alpine
          name: redis
          ports:
          - containerPort: 6379
            name: redis
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/redis" 
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-frontend
  labels:
    app: cloud.greyscale.pe.kr
    tier: frontend
    version: "20180609"
spec:
  ports:
    - port: 80
      nodePort: 31011
      name: http
  selector:
    app: cloud.greyscale.pe.kr
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-nginx
  labels:
    app: cloud.greyscale.pe.kr
    tier: frontend
    version: "20180609"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud.greyscale.pe.kr
        tier: frontend
        version: "20180609"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          env:
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
          - name: htdocs
            mountPath: /var/www/html
          - name: conf
            mountPath: /etc/nginx/conf.d
          - name: log
            mountPath: /var/log/nginx
          - name: dir-documents
            mountPath: /mnt/documents
          - name: dir-non-criticals
            mountPath: /mnt/non-criticals
          - name: dir-torrents
            mountPath: /mnt/torrents
      volumes:
        - name: htdocs
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/nextcloud"
        - name: conf
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/nginx-conf"
        - name: log
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/nginx-log"
        - name: dir-documents
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/documents"
        - name: dir-non-criticals
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/non-criticals"
        - name: dir-torrents
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/torrents"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-webapp
  labels:
    app: cloud.greyscale.pe.kr
    tier: webapp
    version: "20180609"
spec:
  ports:
    - port: 9000
      name: php-fpm
  selector:
    app: cloud.greyscale.pe.kr
    tier: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-nextcloud
  labels:
    app: cloud.greyscale.pe.kr
    tier: webapp
    version: "20180609"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud.greyscale.pe.kr
        tier: webapp
        version: "20180609"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: nextcloud:fpm
          name: nextcloud
          env:
          - name: POSTGRES_HOST
            value: cloud-db
          - name: POSTGRES_DB
            value: nextcloud
          - name: POSTGRES_USER
            value: nextcloud
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloud-db-pass
                key: password
          ports:
          - containerPort: 9000
            name: php-fpm
          volumeMounts:
          - name: htdocs
            mountPath: /var/www/html
          - name: dir-documents
            mountPath: /mnt/documents
          - name: dir-non-criticals
            mountPath: /mnt/non-criticals
          - name: dir-torrents
            mountPath: /mnt/torrents
      volumes:
        - name: htdocs
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/nextcloud" 
        - name: dir-documents
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/documents"
        - name: dir-non-criticals
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/non-criticals"
        - name: dir-torrents
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/torrents"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloud-cronjob
  labels:
    app: cloud.greyscale.pe.kr
    tier: cronjob
    version: "20180609"
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cloud.greyscale.pe.kr
            tier: cronjob
            version: "20180609"
          annotations:
            "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: nextcloud
            image: nextcloud:fpm
            args:
            - "su"
            - "-"
            - "www-data"
            - "-s"
            - "/bin/sh"
            - "-c"
            - "php -f /var/www/html/cron.php"
            volumeMounts:
            - name: htdocs
              mountPath: /var/www/html
            - name: dir-documents
              mountPath: /mnt/documents
            - name: dir-non-criticals
              mountPath: /mnt/non-criticals
            - name: dir-torrents
              mountPath: /mnt/torrents
          volumes:
            - name: htdocs
              nfs:          
                server: 192.168.10.3
                path: "/mnt/bay_array/container-persistents/cloud.greyscale.pe.kr/nextcloud" 
            - name: dir-documents
              nfs:          
                server: 192.168.10.3
                path: "/mnt/bay_array/documents"
            - name: dir-non-criticals
              nfs:          
                server: 192.168.10.3
                path: "/mnt/bay_array/non-criticals"
            - name: dir-torrents
              nfs:          
                server: 192.168.10.3
                path: "/mnt/bay_array/torrents"            

