---
apiVersion: v1
kind: Service
metadata:
  name: torrent-flood
  labels:
    app: flood.greyscale.pe.kr
    tier: monolithic
    version: "20180609"
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31015
      name: webgui
    - port: 49184
      nodePort: 31016
      name: p2p-tcp
    - port: 49184
      nodePort: 31016
      protocol: UDP
      name: p2p-udp
  selector:
    app: flood.greyscale.pe.kr
    tier: monolithic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: torrent-flood
  labels:
    app: flood.greyscale.pe.kr
    tier: monolithic
    version: "20180609"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flood.greyscale.pe.kr
        tier: monolithic
        version: "20180609"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"a.b.c.d/24\"]"
    spec:
      containers:
        - image: wonderfall/rtorrent-flood
          name: rtorrent-flood
          tty: true
          env:
          - name: UID
            value: "0"
          - name: GID
            value: "0"
          - name: FLOOD_SECRET
            valueFrom:
              secretKeyRef:
                name: flood-secret
                key: password
          - name: CONTEXT_PATH
            value: "/"
          - name: RTORRENT_SCGI
            value: "0"
          - name: PKG_CONFIG_PATH
            value: "/usr/local/lib/pkgconfig"
          ports:
          - containerPort: 3000
            name: webgui
          - containerPort: 49184
            name: p2p-tcp
          - containerPort: 49184
            protocol: UDP
            name: p2p-udp
          volumeMounts:
          - name: data
            mountPath: /data
          - name: flood-db
            mountPath: /flood-db
      volumes:
        - name: flood-db
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
        - name: data
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
---

