---
apiVersion: v1
kind: Service
metadata:
  name: vcs-webgui
  labels:
    app: git.greyscale.pe.kr
    tier: monolithic
    version: "20180609"
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31012
      name: vcs-webgui
  selector:
    app: git.greyscale.pe.kr
    tier: monolithic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vcs-scm-manager
  labels:
    app: git.greyscale.pe.kr
    tier: monolithic
    version: "20180609"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: git.greyscale.pe.kr
        tier: monolithic
        version: "20180609"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: sdorra/scm-manager:latest
          name: scm-manager
          ports:
          - containerPort: 8080
            name: vcs-webgui
          volumeMounts:
          - name: repositories
            mountPath: /var/lib/scm
      volumes:
        - name: repositories
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/vcs"
---

