---
apiVersion: v1
kind: Service
metadata:
  name: media-stream
  labels:
    app: plex.greyscale.pe.kr
    tier: monolithic
    version: "20180608"
spec:
  type: NodePort
  ports:
    - port: 32400
      nodePort: 31002
      name: access
    - port: 3005
      nodePort: 31003
      name: home-theater
    - port: 8324
      nodePort: 31004
      name: roku
    - port: 32469
      nodePort: 31005
      name: dlna-tcp
    - port: 1900
      nodePort: 31006
      protocol: UDP
      name: dlna-udp
    - port: 32410
      nodePort: 31007
      name: gdm-net-1
      protocol: UDP
    - port: 32412
      nodePort: 31008
      name: gdm-net-2
      protocol: UDP
    - port: 32413
      nodePort: 31009
      name: gdm-net-3
      protocol: UDP
    - port: 32414
      nodePort: 31010
      name: gdm-net-4
      protocol: UDP
  selector:
    app: plex.greyscale.pe.kr
    tier: monolithic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-plex
  labels:
    app: plex.greyscale.pe.kr
    tier: monolithic
    version: "20180608"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex.greyscale.pe.kr
        tier: monolithic
        version: "20180608"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"a.b.c.d/24\"]"
    spec:
      containers:
        - image: plexinc/pms-docker:plexpass
          name: plexmediaserver-plexpass
          env:
          - name: PLEX_UID
            value: "0"
          - name: PLEX_GID
            value: "0"
          - name: CHANGE_CONFIG_DIR_OWNERSHIP
            value: "false"
          - name: TZ
            value: "KR"
          - name: ALLOWED_NETWORKS
            value: "a.b.c.d/24,a.b.c.d/24"
          - name: PLEX_CLAIM 
            valueFrom:
              secretKeyRef:
                name: media-stream-claim
                key: token
          - name: ADVERTISE_IP
            value: "http://a.b.c.d:32400"
          ports:
          - containerPort: 32400
            name: access
          - containerPort: 3005
            name: home-theater
          - containerPort: 8324
            name: roku
          - containerPort: 32469
            name: dlna-tcp
          - containerPort: 1900
            protocol: UDP
            name: dlna-udp
          - containerPort: 32410
            name: gdm-net-1
            protocol: UDP
          - containerPort: 32412
            name: gdm-net-2
            protocol: UDP
          - containerPort: 32413
            name: gdm-net-3
            protocol: UDP
          - containerPort: 32414
            name: gdm-net-4
            protocol: UDP          
          volumeMounts:
          - name: config
            mountPath: /config
          - name: transcode
            mountPath: /transcode
          - name: data
            mountPath: /data
          - name: certs
            mountPath: /usr/local/etc/certs-vol
      volumes:
        - name: config
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
        - name: transcode
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
        - name: data
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
        - name: certs
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
