---
apiVersion: v1
kind: Service
metadata:
  name: torrent-tr1
  labels:
    app: tr1.greyscale.pe.kr
    tier: monolithic
    version: "20180608"
spec:
  type: NodePort
  ports:
    - port: 9091
      nodePort: 31013
      name: daemon
    - port: 51413
      nodePort: 31014
      name: p2p-tcp
    - port: 51413
      nodePort: 31014
      protocol: UDP
      name: p2p-udp
  selector:
    app: tr1.greyscale.pe.kr
    tier: monolithic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: torrent-transmission
  labels:
    app: tr1.greyscale.pe.kr
    tier: monolithic
    version: "20180608"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tr1.greyscale.pe.kr
        tier: monolithic
        version: "20180608"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"a.b.c.d/24\"]"
    spec:
      containers:
        - image: linuxserver/transmission
          name: transmission
          command: ["bin/sh", "-ec", "mkdir -p /usr/local/etc/transmission/home && ln -s /downloads /usr/local/etc/transmission/home/Downloads && mkdir -p /home/transmission && ln -s /downloads /home/transmission/Downloads && /init"]
          env:
          - name: TZ
            value: KR
          ports:
          - containerPort: 9091
            name: daemon
          - containerPort: 51413
            name: p2p-tcp
          - containerPort: 51413
            protocol: UDP
            name: p2p-udp
          volumeMounts:
          - name: config
            mountPath: /config
          - name: downloads
            mountPath: /downloads
          - name: watch
            mountPath: /watch
      volumes:
        - name: config
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
        - name: downloads
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
        - name: watch
          nfs:          
            server: a.b.c.d
            path: "path_for_mount"
---
