apiVersion: v1
kind: Service
metadata:
  name: wiki-db
  labels:
    app: wiki.greyscale.pe.kr
    tier: db
    version: "20180610"
spec:
  ports:
    - port: 5432
      name: postgresql
  selector:
    app: wiki.greyscale.pe.kr
    tier: db
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wiki-postgresql
  labels:
    app: wiki.greyscale.pe.kr
    tier: db
    version: "20180610"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wiki.greyscale.pe.kr
        tier: db
        version: "20180610"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: postgres:alpine
          name: postgresql
          env:
          - name: POSTGRES_USER
            value: mediawiki
          - name: POSTGRES_DB
            value: mediawiki
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wiki-db-pass
                key: password
          ports:
          - containerPort: 5432
            name: postgresql
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/wiki.greyscale.pe.kr/postgresql" 
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-cache-db
  labels:
    app: wiki.greyscale.pe.kr
    tier: cache-db
    version: "20180610"
spec:
  ports:
    - port: 11211
      name: memcached
  selector:
    app: wiki.greyscale.pe.kr
    tier: cache-db
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wiki-memcached
  labels:
    app: wiki.greyscale.pe.kr
    tier: cache-db
    version: "20180610"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wiki.greyscale.pe.kr
        tier: cache-db
        version: "20180610"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: memcached:alpine
          name: memcached
          ports:
          - containerPort: 11211
            name: memcached
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-frontend
  labels:
    app: wiki.greyscale.pe.kr
    tier: frontend
    version: "20180610"
spec:
  ports:
    - port: 80
      nodePort: 31017
      name: http
  selector:
    app: wiki.greyscale.pe.kr
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wiki-nginx
  labels:
    app: wiki.greyscale.pe.kr
    tier: frontend
    version: "20180610"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wiki.greyscale.pe.kr
        tier: frontend
        version: "20180610"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          env:
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
          - name: htdocs
            mountPath: /var/www/mediawiki
          - name: conf
            mountPath: /etc/nginx/conf.d
          - name: log
            mountPath: /var/log/nginx
      volumes:
        - name: htdocs
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/wiki.greyscale.pe.kr/mediawiki"
        - name: conf
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/wiki.greyscale.pe.kr/nginx-conf"
        - name: log
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/wiki.greyscale.pe.kr/nginx-log"
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-webapp
  labels:
    app: wiki.greyscale.pe.kr
    tier: webapp
    version: "20180610"
spec:
  ports:
    - port: 9000
      name: php-fpm
  selector:
    app: wiki.greyscale.pe.kr
    tier: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wiki-mediawiki
  labels:
    app: wiki.greyscale.pe.kr
    tier: webapp
    version: "20180610"
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wiki.greyscale.pe.kr
        tier: webapp
        version: "20180610"
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.55.2.0/24\"]"
    spec:
      containers:
        - image: mediawiki:alpine-fpm-custom
          imagePullPolicy: IfNotPresent
          name: mediawiki
          ports:
          - containerPort: 9000
            name: php-fpm
          volumeMounts:
          - name: htdocs
            mountPath: /var/www/mediawiki
      volumes:
        - name: htdocs
          nfs:          
            server: 192.168.10.3
            path: "/mnt/bay_array/container-persistents/wiki.greyscale.pe.kr/mediawiki" 
---
